### ISSUE TITLE
FEATURE: UI test dsl (AndroidMakers)

### ISSUE THREAD

**Issue by cpeppas** [TWiStErRob/android-real-skeleton#1]
I just watched your excellent talk in [AndroidMakers](https://www.youtube.com/watch?v=wlb3lg5JocA) and I am interested to see the code and possible examples whenever possible.

Thanks

**Comment by TWiStErRob** [comment]
Sorry for the delay, couldn't find the time.

These were the focus of the talk: [gwen](https://github.com/TWiStErRob/android-realistic/commit/aebcbded368a32e1eab71901b607f669494ec141) + [DSL](https://github.com/TWiStErRob/android-realistic/commit/006e6b31ef28e55da1e41fccee85fdea8641b103) + [Tests](https://github.com/TWiStErRob/android-realistic/commit/700c7910cc64f04a919f3ce07f649a1c18a84908)

**Comment by cpeppas** [comment]
no worries..thanks a lot!
